version: "3"
services:
  web:
    image: nginx:latest
    ports:
      - "8081:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/site.conf:/etc/nginx/conf.d/default.conf
    networks:
      - database
    depends_on:
      - php
  php:
    image: php7mysql
    build:
      context: "./docker/php/"
    volumes:
      - ./:/var/www
    networks:
      - database
    depends_on:
      - service-stock-mysql
  service-stock-mysql:
    image: mysql:5.7
    networks:
      - database
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: stock
      MYSQL_USER: rseixas
      MYSQL_PASSWORD: root
    volumes:
      - ./database.sql:/docker-entrypoint-initdb.d/dump.sql

networks:
  database:
    driver: bridge
